# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'indice_ndwi_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndiceNDWIDialogBase(object):
    def setupUi(self, IndiceNDWIDialogBase):
        IndiceNDWIDialogBase.setObjectName("IndiceNDWIDialogBase")
        IndiceNDWIDialogBase.setEnabled(True)
        IndiceNDWIDialogBase.resize(960, 400)
        IndiceNDWIDialogBase.setMinimumSize(QtCore.QSize(960, 400))
        IndiceNDWIDialogBase.setMaximumSize(QtCore.QSize(960, 400))
        self.label_74 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.label_74.setGeometry(QtCore.QRect(20, 160, 921, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.label_74.setStyleSheet("background-color :#919191; color : white")
        self.label_74.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_74.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.label_75.setGeometry(QtCore.QRect(20, 260, 921, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.label_75.setStyleSheet("background-color : #919191; color : white")
        self.label_75.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_75.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_75.setObjectName("label_75")
        self.label_37 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.label_37.setGeometry(QtCore.QRect(20, 50, 921, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMaximumSize(QtCore.QSize(60000, 16777215))
        self.label_37.setMouseTracking(False)
        self.label_37.setStyleSheet("background-color : #919191; color : white")
        self.label_37.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_37.setObjectName("label_37")
        self.btn_inst = QtWidgets.QPushButton(IndiceNDWIDialogBase)
        self.btn_inst.setGeometry(QtCore.QRect(390, 10, 181, 27))
        self.btn_inst.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_inst.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_inst.setObjectName("btn_inst")
        self.msj_MTL = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.msj_MTL.setGeometry(QtCore.QRect(20, 120, 229, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_MTL.sizePolicy().hasHeightForWidth())
        self.msj_MTL.setSizePolicy(sizePolicy)
        self.msj_MTL.setMinimumSize(QtCore.QSize(229, 27))
        self.msj_MTL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_MTL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_MTL.setObjectName("msj_MTL")
        self.cuadroMTL = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroMTL.setGeometry(QtCore.QRect(240, 120, 661, 27))
        self.cuadroMTL.setMinimumSize(QtCore.QSize(0, 27))
        self.cuadroMTL.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroMTL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroMTL.setText("")
        self.cuadroMTL.setObjectName("cuadroMTL")
        self.btn_abrirMTL = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirMTL.setGeometry(QtCore.QRect(910, 120, 27, 27))
        self.btn_abrirMTL.setMinimumSize(QtCore.QSize(0, 27))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/MTL.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abrirMTL.setIcon(icon)
        self.btn_abrirMTL.setObjectName("btn_abrirMTL")
        self.msj_TIF = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.msj_TIF.setGeometry(QtCore.QRect(20, 80, 229, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_TIF.sizePolicy().hasHeightForWidth())
        self.msj_TIF.setSizePolicy(sizePolicy)
        self.msj_TIF.setMinimumSize(QtCore.QSize(229, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.msj_TIF.setFont(font)
        self.msj_TIF.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_TIF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_TIF.setObjectName("msj_TIF")
        self.cuadroTIF = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroTIF.setEnabled(True)
        self.cuadroTIF.setGeometry(QtCore.QRect(240, 80, 661, 27))
        self.cuadroTIF.setMinimumSize(QtCore.QSize(27, 27))
        self.cuadroTIF.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroTIF.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroTIF.setText("")
        self.cuadroTIF.setObjectName("cuadroTIF")
        self.btn_abrirTIF = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirTIF.setGeometry(QtCore.QRect(910, 80, 27, 27))
        self.btn_abrirTIF.setMinimumSize(QtCore.QSize(0, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/imag_bruto.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abrirTIF.setIcon(icon1)
        self.btn_abrirTIF.setObjectName("btn_abrirTIF")
        self.msj_CORR = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.msj_CORR.setGeometry(QtCore.QRect(20, 220, 252, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_CORR.sizePolicy().hasHeightForWidth())
        self.msj_CORR.setSizePolicy(sizePolicy)
        self.msj_CORR.setMinimumSize(QtCore.QSize(229, 27))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.msj_CORR.setFont(font)
        self.msj_CORR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_CORR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_CORR.setObjectName("msj_CORR")
        self.cuadroBandasCorregidas = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroBandasCorregidas.setEnabled(True)
        self.cuadroBandasCorregidas.setGeometry(QtCore.QRect(300, 220, 601, 27))
        self.cuadroBandasCorregidas.setMinimumSize(QtCore.QSize(0, 27))
        self.cuadroBandasCorregidas.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroBandasCorregidas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroBandasCorregidas.setText("")
        self.cuadroBandasCorregidas.setObjectName("cuadroBandasCorregidas")
        self.btn_abrirCORR = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirCORR.setGeometry(QtCore.QRect(910, 220, 27, 27))
        self.btn_abrirCORR.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_abrirCORR.setIcon(icon1)
        self.btn_abrirCORR.setObjectName("btn_abrirCORR")
        self.msj_guardar = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.msj_guardar.setGeometry(QtCore.QRect(20, 291, 82, 27))
        self.msj_guardar.setMinimumSize(QtCore.QSize(0, 27))
        self.msj_guardar.setObjectName("msj_guardar")
        self.cuadroGuardar = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroGuardar.setGeometry(QtCore.QRect(130, 290, 771, 27))
        self.cuadroGuardar.setMinimumSize(QtCore.QSize(0, 27))
        self.cuadroGuardar.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroGuardar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroGuardar.setText("")
        self.cuadroGuardar.setObjectName("cuadroGuardar")
        self.btn_guardar = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_guardar.setGeometry(QtCore.QRect(910, 290, 27, 27))
        self.btn_guardar.setMinimumSize(QtCore.QSize(0, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/guardar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_guardar.setIcon(icon2)
        self.btn_guardar.setObjectName("btn_guardar")
        self.btn_ejecutar = QtWidgets.QPushButton(IndiceNDWIDialogBase)
        self.btn_ejecutar.setGeometry(QtCore.QRect(670, 360, 111, 27))
        self.btn_ejecutar.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_ejecutar.setObjectName("btn_ejecutar")
        self.btn_cerrar = QtWidgets.QPushButton(IndiceNDWIDialogBase)
        self.btn_cerrar.setGeometry(QtCore.QRect(790, 360, 111, 27))
        self.btn_cerrar.setMinimumSize(QtCore.QSize(0, 27))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.aviso_ejecutar = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.aviso_ejecutar.setGeometry(QtCore.QRect(340, 330, 564, 31))
        self.aviso_ejecutar.setObjectName("aviso_ejecutar")
        self.btn_correccion = QtWidgets.QCheckBox(IndiceNDWIDialogBase)
        self.btn_correccion.setGeometry(QtCore.QRect(20, 190, 141, 20))
        self.btn_correccion.setObjectName("btn_correccion")

        self.retranslateUi(IndiceNDWIDialogBase)
        QtCore.QMetaObject.connectSlotsByName(IndiceNDWIDialogBase)

    def retranslateUi(self, IndiceNDWIDialogBase):
        _translate = QtCore.QCoreApplication.translate
        IndiceNDWIDialogBase.setWindowTitle(_translate("IndiceNDWIDialogBase", "Moisture and Water Index 2.0"))
        self.label_74.setText(_translate("IndiceNDWIDialogBase", "Corrección atmosférica (Radiancia y reflectancia TOA)"))
        self.label_75.setText(_translate("IndiceNDWIDialogBase", "Cálculo NDWI (Xu, Gao y McFeeters)"))
        self.label_37.setText(_translate("IndiceNDWIDialogBase", "Entrada de datos sin procesar "))
        self.btn_inst.setText(_translate("IndiceNDWIDialogBase", "¿Cómo usar el complemento?"))
        self.msj_MTL.setToolTip(_translate("IndiceNDWIDialogBase", "<html><head/><body><p>Select MTL file (if not in Landsat directory)</p></body></html>"))
        self.msj_MTL.setText(_translate("IndiceNDWIDialogBase", "Seleccionar archivo MTL"))
        self.btn_abrirMTL.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.msj_TIF.setText(_translate("IndiceNDWIDialogBase", "Seleccionar imágenes Landsat 8 "))
        self.btn_abrirTIF.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.msj_CORR.setText(_translate("IndiceNDWIDialogBase", "Seleccionar imágenes corregidas Landsat 8 "))
        self.btn_abrirCORR.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.msj_guardar.setText(_translate("IndiceNDWIDialogBase", "Guardar NDWI"))
        self.btn_guardar.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.btn_ejecutar.setText(_translate("IndiceNDWIDialogBase", "Ejecutar"))
        self.btn_cerrar.setText(_translate("IndiceNDWIDialogBase", "Cerrar"))
        self.aviso_ejecutar.setText(_translate("IndiceNDWIDialogBase", "⚠️AVISO: El botón “Ejecutar” se activará solo cuando ingrese los datos solicitados correctamente."))
        self.btn_correccion.setText(_translate("IndiceNDWIDialogBase", "Corrección realizada "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndiceNDWIDialogBase = QtWidgets.QDialog()
    ui = Ui_IndiceNDWIDialogBase()
    ui.setupUi(IndiceNDWIDialogBase)
    IndiceNDWIDialogBase.show()
    sys.exit(app.exec_())
